site_name: 'python-app'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/vihegde/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - What is Backstage?: 'docs/index.md'